# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: nuget/setup-nuget@v1        
      - run: nuget restore SimpleRules.sln

      
      - name: .Net Build
        # You may pin to the exact commit or the version.
        # uses: EasyDesk/action-dotnet-build@d2c47d8701e3ea8db03dcabaacb37204fe123a22
        uses: EasyDesk/action-dotnet-build@v1.0.0
        #with:
          # Additional build arguments to pass to 'dotnet build'.
          #build-args: # optional
          # The build configuration to use (defaults to 'Release').
          #build-configuration: # optional, default is Release
          # The path to the project or solution to build (defaults to the current directory).
          #path: $({ git

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls ${{ github.workspace }}
      
      
